from typing import Callable, List, Optional, Protocol

from .common import Familiar
from .models import Persona

name_resolver = Callable[[Familiar], str]
saver = Callable[[Persona], Persona]


class PersonasRepository(Protocol):
    def save(self, persona: Persona) -> Persona: ...
    def get_all(self) -> List[Persona]: ...
    def get_by_id(self, id: int) -> Optional[Persona]: ...
    def get_by_dni(self, dni: str) -> Optional[Persona]: ...
    def put(self, id: int, persona: Persona) -> Persona: ...
    def delete(self, id: int) -> None: ...
    def delete_all(self) -> None: ...


class PersonasSerializer(Protocol):
    def import_data(self, path: str, saver: saver) -> None: ...
    def export_data(
        self, personas: List[Persona], name_resolver: name_resolver
    ) -> str: ...
