"""First Migration

Revision ID: 1d63db96399e
Revises: 
Create Date: 2026-05-09 03:40:56.547858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d63db96399e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('extranjero', sa.Boolean(), nullable=False),
    sa.Column('family_owner', sa.Boolean(), nullable=False),
    sa.Column('cargado_en_caritas', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persona'))
    )
    op.create_index(op.f('ix_persona_dni'), 'persona', ['dni'], unique=True)
    op.create_table('grupo_familiar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('fk_grupo_familiar_persona_id_persona'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo_familiar')),
    sa.UniqueConstraint('persona_id', name=op.f('uq_grupo_familiar_persona_id'))
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('localidad', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('fk_ubicacion_persona_id_persona'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ubicacion')),
    sa.UniqueConstraint('persona_id', name=op.f('uq_ubicacion_persona_id'))
    )
    op.create_table('miembro_grupo_familiar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CARGADO', 'DESCONOCIDO', name='familiartipo'), nullable=False),
    sa.Column('relacion', sa.Enum('HIJO', 'CONYUGE', 'PADRE', 'MADRE', 'HERMANO', 'OTRO', name='familiarrelacion'), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_familiar.id'], name=op.f('fk_miembro_grupo_familiar_grupo_id_grupo_familiar'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_miembro_grupo_familiar'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miembro_grupo_familiar')
    op.drop_table('ubicacion')
    op.drop_table('grupo_familiar')
    op.drop_index(op.f('ix_persona_dni'), table_name='persona')
    op.drop_table('persona')
    # ### end Alembic commands ###
